### ISSUE TITLE
Functions not listed out in "Functions" tab

### ISSUE THREAD

**Issue by chengteck** [HanLee/Not-a-debugger#1]
Hi Han Lee.

Thank you for creating and sharing NAD.

I encountered a problem during my usage of NAD.

After hooking my application in the app tab and launching the application, I did not have the functions listed out when I browse to the "Functions" tab.

I have attached a screenshot of this issue.

Did you encounter this issue?

![screenshot from 2017-04-14 00-34-11](https://cloud.githubusercontent.com/assets/8423798/25014485/8889fd64-20aa-11e7-8d9c-a1338585b8dd.png)

**Comment by HanLee** [comment]
Hi chengteck,

Just a few steps to debug:
1) Have you launched the pinstore application? The analysis is only performed during the target application launch, and the function list will be populated when the target application starts. If you have launched the application before it starts, please try stopping the process entirely instead of sending it to the background, and launch it again.

2) What Android version are you using? I have just updated the apk to the latest build, can you try that and see if that solves the problem?

**Comment by chengteck** [comment]
Hi HanLee,

Thanks for the reply.

Have you launched the pinstore application? The analysis is only performed during the target application launch, and the function list will be populated when the target application starts. If you have launched the application before it starts, please try stopping the process entirely instead of sending it to the background, and launch it again.

**What I did earlier was after hooking the pinstore application, I proceed to launch the application.**

What Android version are you using? I have just updated the apk to the latest build, can you try that and see if that solves the problem?

**I am using Android 5.0.2
Are you still uploading the apk?
I see that it's last updated 7 months ago.
nad-server.apk	Adding in nad-server.apk and nad-client.jar	7 months ago**

**Comment by HanLee** [comment]
Hi chengteck,

There were some problems syncing earlier, please try now.

**Comment by chengteck** [comment]
Hi HanLee. 
It's working fine now with the updated apk.
Thanks for the assist!

**Comment by HanLee** [comment]
Great to hear!
